### ISSUE TITLE
User scopes

### ISSUE THREAD

**Issue by simra** [Tech4Tracing/CartridgeOCR#40]
Some users are admins
Users might grant public permissions to annotate their collections
Users might invite specific users to annotate their collections
Users can annotate their own collections

**Comment by monkeypants** [comment]
(somewhat related to #15) We might also want a concept of organizations:
* User is/is-not a member of the organization
* collection belongs to user OR collection belongs to organization
* collection is public-private, because it's owner (user, org) controls that

i.e: the analogy to GitHub:
* annotation platform user (what do we call it BTW?) is like a GitHub user, has a "handle" etc.
* annotation platform organization is like a GitHub organization
* annotation platform collection is like a repository

GitHub has a collection of permissions associated with repositories, and teams (within an organization) with different profiles, etc. The Github analogy might break down when we look at the various permissions that can be given re: 
* Organizations have owners and members. Owners control membership.
* Collections have owners (user or organization). Collection owners control the collection policies.

Collection policies (true/false):
 1. allow public to see the fact that the collection exists (on person/organization page) - default true, if false then only organization members can see that the collection exists (if it's owned by an organization).
 2. allow public to view images in the collection - default true, if false then only organization members can see the images in the collection... etc.
 3. allow public to view annotations on images in the collection - default true
 4. show public the identity of the user who made the annotation - default true
 4. allow public to submit new annotations on images in the collection - default true
 5. moderate-before-accept publicly submitted annotations - default true. This means that when someone "submits" an annotation (who is not the collection owner - if personal collection - or is not in the organization - if organization owned) then it would go into some kind of workflow queue to be accepted/rejected. I'm not sure we need this feature until people are accepting/managing public annotations, maybe never.

That probably covers a multitude of sins. However it's a rude simplification of the GitHub model - there is no way to share access to a private personal collection with selected individuals, for example. But it might be good enough to last for a while.

**Comment by monkeypants** [comment]
This might be hidden under an "advanced access control" option, with the simple options being "public" vs "private". So the collection owner chooses "public", "private" or "advanced". **Public** and **private** options would have preset values for these bools, **advanced** would allow users to set them individually.

**Comment by monkeypants** [comment]
@koriaf is this right:
* we now have `is_superuser` (admin) and `is_active` (not soft-deleted) per 5578c23
* we do have `ImageCollections` (owned by users) 
* we don't have:
   - orgs / org membership / types of org membership (owner, manager, member)
   - each collection either belongs to an org or a person 
   - teams (that belong to orgs) and memberships (people belonging to teams)
   - policies that authorise members of a team to do things to a collection (read, write, delete, etc.)  if it's owned by an org
   - policies that authorise individuals to do things to a collection (owned by org or person)

You didn't respond to the suggestion about orgs @simra - should we add scopes without it? Or should we bite the bullet and do this all in one go?

**Comment by koriaf** [comment]
Yes, it's right regarding what we have and what we don't have.
The collections are owned by users; it's relatively quick to implement giving access to other users (by email is the simplest, by invite link a bit more compliated regarding UI); I think for the MVP orgs==teams (if user can be part of multiple orgs). The whole org/team structure is nice and we can implement it if we have to but I'd rather spent time making the API nice (now it's alpha and don't even have decent error handling - not even error format formalized - UI developers will hate us)

**Comment by simra** [comment]
Agree with all of this. 
I think for now, a collection has an owner. 
It also has other users that have read-only or read/write access.
Only the owner can grant other users permissions.

Later we can get more fine-grained on permissions (add/delete image, add/delete/edit annotation, etc)

You guys probably have a better sense of how to design that- just a single table indexed by collection id indicating the permissions granted?

**Comment by monkeypants** [comment]
So minimum viable:
* collection owner has full permissions
* authorisation table relates collection & person
* authorisation table has as many boolean attributes as we need,
we can keep adding boolean attributes until it starts to get silly, then we replace it with a more clever model

**Comment by simra** [comment]
Basics in place with PR #109
