### ISSUE TITLE
Save metadata for images and annotations

### ISSUE THREAD

**Issue by simra** [Tech4Tracing/CartridgeOCR#48]
Suggest we create a separate table for metadata, indexed by image id + annotation id (or just image id, if the metadata is about an image).  We can store key-value pairs here.  Some things we might formalize, like information about annotations, but we can also let it be free-form so the user can leave notes, add special attributes etc.

This will also require some ui updates in the annotation pane, and (future) image/collection browser.

We might consider also optionally capturing exif data as metadata at image upload time- it might be wise to strip exif data from the raw images anyways.

**Comment by monkeypants** [comment]
There might be quite a few different types of thing here:
* image notes (free text, typed by a person about an image). If the same image appears in multiple collections, this is contextual to a collection. This might be a table with foreign keys to Image and Person (and datetime and text). These might be created when an image is added to a collection, for example.
* annotation notes (free text, typed by a person about an annotation). This is also contextual to an image in a collection. This might be a table with foreign keys to Annotation and Person (and datetime, and text). These could presumably be created when an annotation is made, but they might also be a 3rd party assessment of an annotation. It might be better not to conflate "annotator comments" with "assessment of annotation performance", that might be modeled separately (and later, if/when we really think we need it)
* objective metadata (e.g. exif data, size and shape, codec, etc) that applies to the image once, regardless of how many collections it is added to. This might be new attributes on the Image table.
* subjective metadata (i.e. a "scorecard" generated by a model, about an image). This will be the same (for a given model version) regardless of how many collections the image occurs in, but an image may have many of them that were generated by different models (or different versions of the same model). This might be best as a json field.

About stripping exit metadata: maybe we keep two copies of an image: one with exif info intact (as uploaded loaded, totally unmolested) and one with exif data stripped out (as published/shown to users). This way, the "public version" (sans-exif) is very much like pre-generated (or generated jit if not yet cached) thumbnails per #50.

Suggest we create these as different tables (because of the different relationships): `ImageNote` and `AnnotationNote` first, then iterating the `Image` as we need the new attributes. We might add `Image.raw_file`, `Image.cleaned_file`, `Image.thumbnail` now, and add `Image.exif_data` later when we decide we need it (and we can post-process `Image.raw_file` to get it then). And add a scorecard table when we have models that have something useful to say :)

**Comment by simra** [comment]
Images and annotations might have semi-structured metadata - sometimes it will be free-form notes but sometimes it will be things we care about for rendering or post-processing.  Here's the current view of an annotation (note the ugly json string escaping):
```

{
      "annotation": "123", 
      "geometry": "[{\"x\": 0.7, \"y\": 0.5047732696897375}, {\"x\": 0.5, \"y\": 0.4880668257756563}, {\"x\": 0.6125, \"y\": 0.5906921241050119}]", 
      "id": "d61b208d-2f15-49e9-b2d2-cb8f5591729f", 
      "image_id": "14eb27f9-2ff5-48f5-92c1-410d02d883f3", 
      "metadata_": "{\"mode\": \"radial\", \"direction\": \"outward\", \"symbol\": true}"
    }
```

Ideally the metadata field is a list of key-value pairs and we can pick up the items we need depending on the task (eg extracting pixels or properties for machine learning).  So I agree we want AnnotationNotes but we could probably fold that into a more general table of things that are associated with an annotation, whether or not they are individually structured.  

Also, it would be nice to have a cleaner way to represent the geometry, and maybe we move the ''mode" field to be captured with the geometry (mode is either radial or rectangular and the geometry should be consistent with this).

**Comment by monkeypants** [comment]
This is where I overcomplicate things unesiscarially.

If we really want key/value pair metadata, why not make one of those. Could even normalise it to have a key table and value table (so there's room for documentation on keys)
```
key  image
  |   |
 /|\ /|\
 value
```
But I would have thought that we would want schema-conformant metadata for model output, and different models would have different schemata. This model yields a score between zero and one, that model yields a semantic tensor with a particular shape, etc. More like this
```
[schema]  [image]
      |    |
     /|\  /|\
    [scorecard]--(payload)
```
Where the payload is a json field that complies with the schema.

So actually one schema might be an annotation, and another schema could be a model output. So the "schema" entity is really a "metadata type" entity (which could have a schema as an attribute, allowing payload validation). So I turned your key/value model into a type/payload model.  Postgresql has a nifty [json type](https://www.postgresql.org/docs/current/datatype-json.html) that would be convenient here (allows indexing and querying within a schema from SQL), It means you don't have to do too much silly escaping too. I think there's somewhat equivalent functions on NVARCHAR in  SQL Server.

But maybe annotations are a thing that changes slowly - so we could model them as their own tables, rather than an inner platform, whereas models are wild and wonderful, so it's appropriate to have an inner platform to accommodate ongoing variability. We don't need to put all metadata in the same table.

**Comment by simra** [comment]
From working with images during the hackathon this week, the low-hanging fruit for this task is just to add some facility for free-form notes per-image.

**Comment by simra** [comment]
Added headstamp notes in PR #133
